name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add deb-src URIs
      run: |
        echo "deb-src http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs) main restricted" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
    - name: checkout headerfiles
      run: apt-get source libdjvulibre-dev; ls
##   - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
