name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Add deb-src URIs
      run: |
        echo "deb-src http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs) main restricted" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update

    - name: install libdjvulibre-dev
      run: sudo apt install libdjvulibre-dev
    - name: voor checokut
      run: pwd
      
    - uses: actions/checkout@v4
    - name: na checokut
      run: pwd
    - name: checkout headerfiles
      run: apt-get source libdjvulibre-dev; ls
    - name: Copy header files
      run: |
        mkdir -p external
        cp -r djvulibre-*/libdjvu/*.h external
        ls external
        ls -ld external
      
    - name: autogen.sh
      run: ./autogen.sh
    - name: show up header files
      run: |
        ls -ld /home/runner/work
        ls -la /home/runner/work

        ls -ld /home/runner/work/revealshapes/revealshapes/external
        ls -la /home/runner/work/revealshapes/revealshapes/external
 
    - name: make
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: revealshapes
        path: revealshapes
